In [ ]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 43.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 38.5 MB/s eta 0:00:00


In [ ]:
!pip install kss

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.7/77.7 KB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 KB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 51.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for kss: filename=kss-4.5.1-py3-none-any.whl size=53218 sha256=34cd3575504490086c2e2d4f98e49a361d5b47a29d41dc40fb666ac93e35f141
  Stored in directory: /root/.cache/pip/wheels/8c/f9/05/a93eb0defc9eed494ee4d42e3d9076fade98f08982f41cf09f
  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646667 sha256=1c6254a47d9b19dd2df34a1ce638da5e82aa1c5e12324b9b6b24c7d867c59c92
  Stored in directory: /root/.cache/pip/wheels/a9/98/a3/085a909aa25805f321467a3af3b80d43b6094ed335b4818775
Successfully built kss pecab


In [ ]:
!pip install contextualized_topic_models

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 783.1/783.1 KB 21.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 76.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 KB 13.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 11.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 80.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 94.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 56.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 82.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 24.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 KB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 KB

In [ ]:
!pip install gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install --upgrade numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 95.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.1 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.1 which is incompatible.
google-colab 1.0.0 requires ipython~=7.9.0, but you have ipython 7.16.3 which is incompatible.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use("fivethirtyeight")
import warnings # 경고 메시지 무시
warnings.filterwarnings(action='ignore')
from tqdm import tqdm # 작업 프로세스 시각화
from nltk import word_tokenize, bigrams #토큰화, 바이그램
from nltk.util import ngrams #트라이그램
from nltk import ConditionalFreqDist #동시출현빈도 계수화
from konlpy.tag import Mecab
import re # 문자열 처리를 위한 정규표현식 패키지
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/suncare_rev_p2.csv', index_col=0)

In [ ]:
df.head()

index     product_id   reviewer  reviewer_rank  specialist  user_score  \
0      0  A000000177783    Goforit              0           0           5   
1      1  A000000177783        설화님            932           0           5   
2      2  A000000177783  pinkyrian              0           0           5   
3      3  A000000177783     kn****              0           0           5   
4      4  A000000177783     Anniee           1116           0           5   

   on_off                                             review  help  year  ...  \
0       0  코로나로 최애 썬크림은 사실 라운드어라운드였어요\n마스크 쓰고 모자쓰니 편하게 쓱쓱...    23  2021  ...   
1       1  💜 건성이며 광 + 톤업이 살짝 되는 순한 선크림을 찾으셨던 분들은 이 제품을 추천...    22  2020  ...   
2       0  넘 써보고 싶었던 톤업 썬크림.\n매장에 가서 테스트 해보고 이번에 새로나온 핑크빛...    17  2021  ...   
3       0  라로슈포제 썬크림은\n멜티드, 틴티드, 아쿠아 젤  써보고 \n톤업을 구입했습니다....    11  2019  ...   
4       0  화장을 정말 잘 안하고 다녔던지라.. 간혹 화장을 하기도 하지만 \n저는 정말 맨얼...     9  2022  ...   

   다크서클  복합성  민감성   미백   지성  발림성  자극도  피부타입_건성에_좋아요  피부타입_복합성에_좋아요  \
0   0.0  0.0  0.0  1.0  0.0    3    3             1              0   
1   0.0  0.0  1.0  0.0  0.0    3    3             1              0   
2   0.0  0.0  1.0  1.0  0.0    3    3             1              0   
3   0.0  0.0  0.0  0.0  0.0    3    3             1              0   
4   1.0  1.0  0.0  0.0  0.0    3    3             0              1   

   피부타입_지성에_좋아요  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 38 columns]

In [ ]:
text = df[['review']]
text.head()

review
0  코로나로 최애 썬크림은 사실 라운드어라운드였어요\n마스크 쓰고 모자쓰니 편하게 쓱쓱...
1  💜 건성이며 광 + 톤업이 살짝 되는 순한 선크림을 찾으셨던 분들은 이 제품을 추천...
2  넘 써보고 싶었던 톤업 썬크림.\n매장에 가서 테스트 해보고 이번에 새로나온 핑크빛...
3  라로슈포제 썬크림은\n멜티드, 틴티드, 아쿠아 젤  써보고 \n톤업을 구입했습니다....
4  화장을 정말 잘 안하고 다녔던지라.. 간혹 화장을 하기도 하지만 \n저는 정말 맨얼...

In [ ]:
text.shape

(2995, 1)

In [ ]:
# 텍스트화된 리뷰 전처리
def RevProcess(rev):
    rev = rev.replace(".", "").strip()
    rev = rev.replace(":", "").strip()
    rev = re.sub('[^가-힣]', ' ', rev)
    rev = rev.replace("  "," ").replace("   ", " ").replace("    "," ").replace("     ", " ").replace("       ", " ")
    return rev

In [ ]:
text['review'] = text.apply(lambda x: RevProcess(x['review']), axis=1)

In [ ]:
text['review']

0       코로나로 최애 썬크림은 사실 라운드어라운드였어요 마스크 쓰고 모자쓰니 편하게 쓱쓱 ...
1        건성이며 광  톤업이 살짝 되는 순한 선크림을 찾으셨던 분들은 이 제품을 추천합니...
2       넘 써보고 싶었던 톤업 썬크림 매장에 가서 테스트 해보고 이번에 새로나온 핑크빛나는...
3       라로슈포제 썬크림은 멜티드 틴티드 아쿠아 젤 써보고 톤업을 구입했습니다 모두 순하고...
4       화장을 정말 잘 안하고 다녔던지라 간혹 화장을 하기도 하지만 저는 정말 맨얼굴에 잘...
                              ...                        
2990    괜찮네요 아무래도 옛날부터 믿고 쓰던 브랜드라 손이 더 갈수빆에 없네요 기대할게요 ...
2991                           너무기름져요  바르면번들번들해서화장할때는못쓸듯요
2992                                                     
2993    아벤느 유명하죠 자극없고 순하기로 그와중에 가격도 만족스러워서 매일 사용하고 있습니...
2994    무향이네요 불투명한 약간 아이보리색나는 크림색제형이고 유분기가 없지는 않지만 너무 ...
Name: review, Length: 2995, dtype: object

In [ ]:
tagger = Mecab()
results = []
for post in text["review"]:
  word_tokens = tagger.pos(post)
  result = [s for s, t in word_tokens if t in ['NNG','XR', 'VA'] and len(s)>1]
  results.append(result)

In [ ]:
len(results)

2995

In [ ]:
text['keyword'] = results

In [ ]:
text['keyword']

0       [최애, 크림, 라운드, 라운드, 모자, 편하, 선호, 자극, 예민, 발림, 라운드...
1       [건성, 선크림, 제품, 추천, 광과, 중요, 사람, 기존, 무기, 자차, 선크림,...
2       [크림, 매장, 테스트, 이번, 핑크, 예쁘, 피부, 표현, 결정, 피부, 요즘, ...
3       [포제, 크림, 멜티, 구입, 순하, 멜티, 느낌, 피부, 깨끗, 정리, 느낌, 멜...
4       [화장, 화장, 얼굴, 나이, 민낯, 부끄럽, 크림, 바르, 번들, 화장, 크림, ...
                              ...                        
2990                            [괜찮, 옛날, 브랜드, 기대, 제품, 가격]
2991                                             [바르, 화장]
2992                                                   []
2993                             [자극, 와중, 가격, 만족, 사용, 화장]
2994    [투명, 아이보리, 크림색, 제형, 유분, 끈덕지, 유분, 상품명, 타입, 생각, ...
Name: keyword, Length: 2995, dtype: object

In [ ]:
# text['keyword'] = text['keyword'].astype(str)

In [ ]:
# text['keyword'] = text['keyword'].apply(lambda x: x.replace('[','').replace(']','').replace("'",'').replace(',',''))

In [ ]:
# text['keyword']

0       최애 크림 라운드 라운드 모자 편하 선호 자극 예민 발림 라운드 라운드 최고 활동 ...
1       건성 선크림 제품 추천 광과 중요 사람 기존 무기 자차 선크림 백탁 워드 사람 제품...
2       크림 매장 테스트 이번 핑크 예쁘 피부 표현 결정 피부 요즘 얼굴 누르끼 얼굴 포제...
3         포제 크림 멜티 구입 순하 멜티 느낌 피부 깨끗 정리 느낌 멜티 조금 하얗 백탁 정도
4       화장 화장 얼굴 나이 민낯 부끄럽 크림 바르 번들 화장 크림 사용 크림 효과 피부 ...
                              ...                        
2990                                   괜찮 옛날 브랜드 기대 제품 가격
2991                                                바르 화장
2992                                                     
2993                                    자극 와중 가격 만족 사용 화장
2994    투명 아이보리 크림색 제형 유분 끈덕지 유분 상품명 타입 생각 당황 피부 민감 선크...
Name: keyword, Length: 2995, dtype: object

In [ ]:
text

review  \
0     코로나로 최애 썬크림은 사실 라운드어라운드였어요 마스크 쓰고 모자쓰니 편하게 쓱쓱 ...   
1      건성이며 광  톤업이 살짝 되는 순한 선크림을 찾으셨던 분들은 이 제품을 추천합니...   
2     넘 써보고 싶었던 톤업 썬크림 매장에 가서 테스트 해보고 이번에 새로나온 핑크빛나는...   
3     라로슈포제 썬크림은 멜티드 틴티드 아쿠아 젤 써보고 톤업을 구입했습니다 모두 순하고...   
4     화장을 정말 잘 안하고 다녔던지라 간혹 화장을 하기도 하지만 저는 정말 맨얼굴에 잘...   
...                                                 ...   
2990  괜찮네요 아무래도 옛날부터 믿고 쓰던 브랜드라 손이 더 갈수빆에 없네요 기대할게요 ...   
2991                         너무기름져요  바르면번들번들해서화장할때는못쓸듯요   
2992                                                      
2993  아벤느 유명하죠 자극없고 순하기로 그와중에 가격도 만족스러워서 매일 사용하고 있습니...   
2994  무향이네요 불투명한 약간 아이보리색나는 크림색제형이고 유분기가 없지는 않지만 너무 ...   

                                                keyword  
0     최애 크림 라운드 라운드 모자 편하 선호 자극 예민 발림 라운드 라운드 최고 활동 ...  
1     건성 선크림 제품 추천 광과 중요 사람 기존 무기 자차 선크림 백탁 워드 사람 제품...  
2     크림 매장 테스트 이번 핑크 예쁘 피부 표현 결정 피부 요즘 얼굴 누르끼 얼굴 포제...  
3       포제 크림 멜티 구입 순하 멜티 느낌 피부 깨끗 정리 느낌 멜티 조금 하얗 백탁 정도  
4     화장 화장 얼굴 나이 민낯 부끄럽 크림 바르 번들 화장 크림 사용 크림 효과 피부 ...  
...                                                 ...  
2990                                 괜찮 옛날 브랜드 기대 제품 가격  
2991                                              바르 화장  
2992                                                     
2993                                  자극 와중 가격 만족 사용 화장  
2994  투명 아이보리 크림색 제형 유분 끈덕지 유분 상품명 타입 생각 당황 피부 민감 선크...  

[2995 rows x 2 columns]

In [ ]:
word_df = pd.read_csv('/content/drive/MyDrive/suncare_total_2 (1).xlsx - Sheet1.csv')

In [ ]:
stopwords = word_df[word_df['태그1'] == 's']['형태소/개체명'].values.tolist()

In [ ]:
for i in stopwords:
  for word in text['keyword']:
    if word == i:
      text['keyword'] = text['keyword'].apply(lambda x: x.replace(i,''))

In [ ]:
for i,j in zip(word_df['형태소/개체명'], word_df['태그1']):
  for word in text['keyword']:
    if i in word:
      text['keyword'] = text['keyword'].apply(lambda x: x.replace(i,j))
    else:
      pass

Streaming output truncated to the last 5000 lines.
['선크림', '구입', '퓨전', '후기', '가격', '물건', '구매', '후기', '확인', '용량', '선크림', '선크림', '용량', '정도', '냄새', '애기', '냄새', '백탁', '복합', '피부']
['사용', '크림', '피부', '자극', '여기저기', '구매', '피부', '순간', '촉촉', '발림', '매끄럽', '파운데이션', '화장', '피부', '마무리', '매트', '보송', '촉촉', '표시', '부분', '제품', '부분', '흔하', '크림', '향도', '공기', '메이크업', '크림', '경우', '시간', '유지', '사용', '얼마', '지금', '느낌', '구매', '의사']
[]
['유면', '선크림', '생각', '옛날', '엄마', '화장품', '냄새', '발림']
['샘플', '기획', '정도', '퓨전', '선크림', '최애', '선크림', '은근', '스타일']
['제품', '사용', '제품', '자극', '제품', '크림', '고민', '사용', '유명', '크림', '사용', '발림', '촉촉', '업도', '느낌', '엄마', '적극', '추천', '엄마', '크림', '사용', '피부', '타입', '엄마', '지성', '복합', '피부', '타입', '괜찮', '크림', '파운데이션', '화장', '느낌', '마음', '마음', '별점', '크림', '예민', '인위', '얼굴', '민감', '손등', '구매']
['무기', '자차', '오랜만', '혼합', '자차', '사용', '시림', '발림', '부드럽', '로션', '정도', '백탁', '자연', '건조', '고민', '후기', '덕분', '감사', '단점', '가격', '대비', '크기', '미니', '미니', '세일']
['피부과', '선크림', '유명', '퓨전', '레이저', '스크린', '유명', '이번', '세일', '기간', '

KeyboardInterrupt: ignored

In [ ]:
text['keyword'][:5]

0    최애 크림 라운드 라운드 모자 편하 선호 자극 예민 발림 라운드 라운드 최고 활동 ...
1    건성 선크림 제품 추천 광과 중요 사람 기존 무기 자차 선크림 백탁 워드 사람 제품...
2    크림 매장 테스트 이번 핑크 예쁘 피부 표현 결정 피부 요즘 얼굴 누르끼 얼굴 라로...
3    라로슈포제 크림 멜티 구매 순하 멜티 느낌 피부 깨끗 정리 느낌 멜티 조금 하얗 백...
4    화장 화장 얼굴 나이 민낯 부끄럽 크림 바르 번들 화장 크림 사용 크림 효과 피부 ...
Name: keyword, dtype: object

In [ ]:
vectorizer = TfidfVectorizer(stop_words=stopwords)
X = vectorizer.fit_transform(text['keyword'])

print('TF-IDF 행렬의 크기 :', X.shape)

TF-IDF 행렬의 크기 : (2995, 2727)


In [ ]:
lda_model = LatentDirichletAllocation(n_components=10,learning_method='online',random_state=1,max_iter=1)

In [ ]:
lda_top = lda_model.fit_transform(X)

In [ ]:
print(lda_model.components_)
print(lda_model.components_.shape)

[[0.17683943 0.13780627 0.13817005 ... 0.13830428 0.1420014  0.14062652]
 [0.59338025 0.14047141 0.22613473 ... 0.14924735 0.14258674 0.13514878]
 [0.13661141 0.14054669 0.1438016  ... 0.14065169 0.14373048 0.14525422]
 ...
 [0.24423333 0.13434079 0.14039256 ... 0.13983369 0.13490407 0.18649789]
 [1.71859187 0.1445023  0.14099911 ... 0.14465596 0.13932623 0.13742635]
 [1.07116781 0.13539863 0.13520608 ... 0.13975753 0.13843574 0.18241878]]
(10, 2727)


In [ ]:
# 단어 집합. 1,000개의 단어가 저장됨.
terms = vectorizer.get_feature_names()

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n - 1:-1]])

get_topics(lda_model.components_,terms)

Topic 1: [('임성', 1.71), ('러플', 1.36), ('어둡', 1.03), ('조카', 0.95), ('생후', 0.78)]
Topic 2: [('최고', 6.76), ('아깝', 4.02), ('업도', 4.01), ('제품', 3.79), ('사용', 3.2)]
Topic 3: [('통째', 3.13), ('뿌듯', 1.44), ('적창', 1.27), ('탁고', 0.9), ('냉장고', 0.83)]
Topic 4: [('혈색', 1.56), ('유광', 1.55), ('든든', 1.3), ('매합', 1.12), ('피해', 1.03)]
Topic 5: [('아토피', 4.71), ('단종', 1.74), ('파라', 1.41), ('동봉', 1.3), ('역대', 1.17)]
Topic 6: [('선크림', 199.31), ('사용', 186.07), ('피부', 181.53), ('제품', 179.51), ('구매', 144.71)]
Topic 7: [('궁중', 1.32), ('몇일', 1.3), ('약국', 1.27), ('친구', 1.23), ('발광', 1.07)]
Topic 8: [('민낯', 4.3), ('케이', 1.64), ('분홍빛', 0.79), ('실패', 0.72), ('어법', 0.69)]
Topic 9: [('물건', 2.96), ('상품명', 2.86), ('업라이트', 2.79), ('유일', 2.61), ('밀봉', 2.6)]
Topic 10: [('기름기', 6.67), ('선물', 4.34), ('건성', 3.99), ('구매', 3.45), ('괜찮', 3.41)]
